spring:

  application:
    name: easybank

  profiles:
    active: default

  security:
    user:
      name: admin
      password: admin

logging:
  level: 
    org:
      springframework:
        security: TRACE
  pattern:
    console: "%green(%d{HH:mm:ss.SSS} %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n)"
